# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign.runs/synth_1/.Xil/Vivado-10576-LAPTOP-4QDNAKBV/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tcsg324-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    c:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/ip/data_ram
    c:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/ip/inst_ram
  } D:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
      rt::read_verilog -include {
    c:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/ip/data_ram
    c:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/ip/inst_ram
  } {
      C:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/rtls/adder.v
      C:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign.srcs/sources_1/new/alu_57inst.v
      C:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign.srcs/sources_1/new/aludec_57inst.v
      C:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/rtls/controller.v
      C:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/rtls/datapath.v
      C:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/rtls/flopenrc.v
      C:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/rtls/floprc.v
      C:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/rtls/hazard_unit.v
      C:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign.srcs/sources_1/new/maindec.v
      C:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/rtls/mips.v
      C:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/rtls/mux2x1_32.v
      C:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/rtls/mux2x1_5.v
      C:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/rtls/mux3x1_forward.v
      C:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/rtls/mux4x1_forwardD.v
      C:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/rtls/pc.v
      C:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/rtls/regfile.v
      C:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign.srcs/sources_1/new/sign_extend_57inst.v
      C:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/rtls/sl2.v
      C:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/rtls/top.v
    }
      rt::read_vhdl -lib blk_mem_gen_v8_4_4 c:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/ip/data_ram/hdl/blk_mem_gen_v8_4_vhsyn_rfs.vhd
      rt::read_vhdl -lib xil_defaultlib {
      c:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/ip/data_ram/synth/data_ram.vhd
      c:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/ip/inst_ram/synth/inst_ram.vhd
    }
      rt::read_vhdl -lib xpm D:/Xilinx/Vivado/2019.2/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter enableSplitFlowPath "C:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign.runs/synth_1/.Xil/Vivado-10576-LAPTOP-4QDNAKBV/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
