# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/ip/data_ram/data_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==data_ram || ORIG_REF_NAME==data_ram} -quiet] -quiet

# IP: C:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/ip/inst_ram/inst_ram.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==inst_ram || ORIG_REF_NAME==inst_ram} -quiet] -quiet

# XDC: c:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/ip/data_ram/data_ram_ooc.xdc

# XDC: c:/Users/Finger_Leader/Desktop/с╡вш/hardwareSynthesisDesign/HardwareSynthesisDesign/HardwareSynthesisDesign/ip/inst_ram/inst_ram_ooc.xdc
